version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
  ignore:
  - dependency-name: ply
    update-types:
    - version-update:semver-major
  - dependency-name: numpy
    update-types:
    - version-update:semver-major
  - dependency-name: PyOpenGL
    update-types:
    - version-update:semver-major
- package-ecosystem: pip
  directory: /Libraries/PyKotor
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  commit-message:
    prefix: chore(pykotor)
    include: scope
- package-ecosystem: pip
  directories:
    - /Tools/*
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  commit-message:
    prefix: chore
    include: scope
